SINGLE_GAME_COLUMNS = [
    "team_score",
    "opp_score",
    "team_fg",
    "team_fga",
    "team_fgp",
    "team_3p",
    "team_3pa",
    "team_3pp",
    "team_ft",
    "team_fta",
    "team_ftp",
    "team_orb",
    "team_trb",
    "team_ast",
    "team_stl",
    "team_blk",
    "team_tov",
    "team_pf",
    "opp_fg",
    "opp_fga",
    "opp_fgp",
    "opp_3p",
    "opp_3pa",
    "opp_3pp",
    "opp_ft",
    "opp_fta",
    "opp_ftp",
    "opp_orb",
    "opp_trb",
    "opp_ast",
    "opp_stl",
    "opp_blk",
    "opp_tov",
    "opp_pf",
]

STRING_FIELDS = ["home", "away", "team_wl"]

CLEANED_GAMELOG_PATH = "data/cleaned_nba_gamelog.csv"
